//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalPatientClinicApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedule
    {
        public int DSid { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public Nullable<System.TimeSpan> AvailableTime { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
